### ISSUE TITLE
extending dump_ast

### ISSUE THREAD

**Issue by acornejo** [sztomi/code-generator#1]
I wanted to extend dump_ast to print out the names and types of the arguments to functions.

For example, consider the following test.h file:

```
SomeType foo (AnotherType a, AnotherType b);
```

Lets suppose SomeType and AnotherType could be defined in another header file.

Currently running dump_ast.h returns the following:

```
./dump_ast.py test.h 
TRANSLATION_UNIT test.h
  +--TYPEDEF_DECL __int128_t
  +--TYPEDEF_DECL __uint128_t
  +--TYPEDEF_DECL __builtin_va_list
  |  +--TYPE_REF __va_list_tag
  +--FUNCTION_DECL foo
```

There is no real useful information about foo here, I would like to know that it receives two parameters named a and b of type `AnotherType`, and that it returns a parameter of `SomeType`. I would like to think this should be possible using the clang api, unfortunately I haven't been able to do this.

By using the `get_arguments()` (as opposed to only `get_children()`) I am able to get the names of the input parameters of a function, but I can't get the names of their types. Suggestions?

**Comment by sztomi** [comment]
Hi, 

Sorry for replying this late, I must have missed the notification.

I recall I had similar trouble with parsing argument types, too. It appears that the support for this is incomplete in libclang. You have two options: go for full-blown libtooling and just use that, it gives you all clang internals and AST matchers which are really nice to work with (i.e. nothing is hidden from the AST). The downside is that you have to use C++ for libtooling. 

The other way can be what I did: when you see a FUNCTION_DECL, take the source line and parse it yourself. It means you lose the accuracy of the C++ compiler, but using [pyPEG](http://fdik.org/pyPEG/) I was able to construct an declaration parser that was able to parse fairly complicated templated various qualified arguments. Stay away from regex though, it's not worth it (and it's not a bandwagon argument linking the zalgo post on SO, it really is impossible to correctly parse even simple cases). Unfortunately I can't share my pyPEG parser because it's under a NDA.
