### ISSUE TITLE
error running generated python code

### ISSUE THREAD

**Issue by rashadkm** [sztomi/code-generator#3]
I had run ./build.sh and here is the output.
Building configurations...
Running action 'gmake'...
Generating Makefile...
Generating codegen.make...
Done.
==== Building codegen (debug) ====
textcomponent.h.bind.cc
Linking codegen

I got a test.py file in src/

When I launch test.py, I am getting below error.
python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import CodegenExample
ImportError: No module named CodegenExample

there is no so file generated or atleast the step is missing. 
can you tell what did I missed?

I am very much interested in this automatic python generator and would like to apply this onto a large  c++ library. I should also mention there is a heavy use of template in the target library.

**Comment by sztomi** [comment]
Hi,

> there is no so file generated or atleast the step is missing. 

The compilation output will be in the build directory, so you need to run from there or adjust your PYPATH. 

> I am very much interested in this automatic python generator and would like to apply this onto a large c++ library. I should also mention there is a heavy use of template in the target library.

This repository accompanies [my article](http://szelei.me/code-generator/) and not really intended as a general solution. The article outlines techniques which can be used to implement code generators.

 For a full-blown solution I'd suggest taking a look at [shiboken](http://wiki.qt.io/PySide_Binding_Generation_Tutorial) which generates more efficent bindings by directly calling the Python C API instead of Boost.Python code.
